apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: generic
spec:
  generic:
    example:
      insecure: true
      # URL of the gRPC server that implements event source
      url: "generic-event-source-server.argo-events.svc:8080"
      # Config represents the configuration required to run the event source
      config: |-
        key1: value1
        key2: value2
